version: "3.9"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo4
    ports:
      - "3306:3306"
    networks:
      - todo

networks:
  todo:
    driver: bridge