version: "3.9"

services:
  db:
    container_name: my_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo4
    volumes:
      - ./database/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo
  backend:
    container_name: my_todo
    image: arvians/go-todo-list:latest
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DBNAME=todo4
    ports:
      - "3030:3030"
    networks:
        - todo

networks:
  todo:
    driver: bridge