CREATE TABLE IF NOT EXISTS todos(
   todo_id INTEGER NOT NULL AUTO_INCREMENT,
   activity_group_id INTEGER NOT NULL,
   title VARCHAR (100) NOT NULL,
   priority VARCHAR (100) NOT NULL,
   is_active BOOLEAN NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (todo_id),
   FOREIGN KEY (activity_group_id) REFERENCES activities(activity_id) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = InnoDB;