CREATE TABLE IF NOT EXISTS activities(
   activity_id INTEGER NOT NULL AUTO_INCREMENT,
   title VARCHAR (100) NOT NULL,
   email VARCHAR (100) UNIQUE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (activity_id)
) ENGINE = InnoDB;